# ==========================================
# Project R3APΞX - Routing Ruleset
# ==========================================

[General]
private-ip-answer = true
ipv6 = true

[URL Rewrite]
# [Option A: Legacy Node (1:1 Real-time)]
# This node is enabled by default.
^https://.*\.cloudcell.com/.* https://rr3.modio.dpdns.org/legacy 302

# [Option B: Accelerated Round Hub Node (6x Time-Warp)]
# To use the Round Hub node, remove the '#' at the beginning of the line below, 
# and add a '#' to comment out the Option A rule.
# ^https://.*\.cloudcell.com/.* https://rr3.modio.dpdns.org/roundhub 302

[MITM]
# Enable Man-in-the-Middle (MITM) decryption for official game server domains. 
# This is strictly required for HTTPS traffic redirection to work.
hostname = cloudcell.com
enable = true
